#ifndef __ERROR_H__
#define __ERROR_H__

#define NO_ERROR 0
#define INDEX_ERROR_INVALID_CHAR 1
#define INDEX_ERROR_INVALID_FILE_DECODER 2
#define INDEX_ERROR_WRITING_STREAM 3
#define INDEX_ERROR_READING_STREAM 4

#endif
